data:
  id: ascadv2
  target_byte: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  target_variable: subbytes
  preprocessing: standardize
  random_roll_scale: 4.
  random_lpf_scale: 0.
  val_prop: 0.2
training:
  total_steps: 500000
  lr_warmup_frac: 0.05
  lr_const_frac: 0.
  batch_size: 64
  base_lr: 8.e-4
  lr_decay_multiplier: 0.001
  weight_decay: 1.e-4
  label_smoothing: 0.
  mixup_alpha: 0.
  additive_gaussian_noise: 0.
  grad_clip_val: 1.
  accumulate_grad_batches: 1
  early_stop_metric: val/rank
  early_stop_mode: min
  seed: 0
  compile: true
  num_workers: 8
mtd:
  attack_count: 1000
  traces_per_attack: 1000
model:
  grey_box_head: ascadv2
  leakage_model: id
  trunk: transformer
  position_embedding: rope
  pooling: token
  head: tied
  fnn_style: mlp
  patch_size: 10000
  use_fourier_embed: false
  fourier_embed_num_bands: null
  fourier_embed_sigma: null
  embedding_dim: 768
  expansion_factor: 4
  trunk_blocks: 8
  head_count: null
  register_tokens: 0
  input_dropout_rate: 0.1
  input_droppatch_rate: 0.
  hidden_dropout_rate: 0.1
  use_bias: false
  perceiver_latent_dim: null
  perceiver_self_attn_per_cross_attn_blocks: null
  perceiver_cross_attn_head_count: null
search_space:
  data:
    random_roll_scale:
      type: categorical
      choices: [0., 1., 2., 4., 8., 16., 32., 64.]
  training:
    base_lr:
      type: float
      low: 1.e-5
      high: 3.e-3
      log: true
    lr_decay_multiplier:
      type: categorical
      choices: [1.]
  model:
    leakage_model:
      type: categorical
      choices: [bit, id, hw]
    grey_box_head:
      type: categorical
      choices: [ascadv2, null]
    patch_size:
      type: categorical
      choices: [5000, 10000, 20000, 40000]
    embedding_dim:
      type: int
      low: 128
      high: 1024
      step: 128
    trunk_blocks:
      type: int
      low: 1
      high: 8
    input_dropout_rate:
      type: float
      low: 0.0
      high: 0.5
      step: 0.1
    hidden_dropout_rate:
      type: float
      low: 0.0
      high: 0.5
      step: 0.1